server:
  port: 8088

spring:
 datasource:
  url: jdbc:h2:mem:fase3db;DB_CLOSE_DELAY=-1
  username: fiapgrupo8
  password: fiapgrupo8
 h2:
  console:
    enabled: true 
    path: /h2
 jpa:
  show-sql: true 
  generate-ddl: true