insert into tb_product (name,brand,description,is_vegan,is_vegetarian,is_gluten_free,price,image_url,rating,qnt_stock) values ('Hambúrguer Vegetal 230g Verdali', 'Verdali', 'Não contém glúten. Contém derivados de soja.', TRUE, TRUE, TRUE, 18.90,'https://cdn.dooca.store/2847/products/verdali-hamburguer-vegetal_1600x1600+fill_ffffff.png?v=1621189496', 3, 150);
insert into tb_product (name,brand,description,is_vegan,is_vegetarian,is_gluten_free,price,image_url,rating,qnt_stock) values ('Camaráo de Soja 300g Goshen', 'Emporio 4 Estrelas', 'Sem lactose. Sem ovo. Vegetariano e vegano.', TRUE, FALSE, FALSE, 22.69,'https://vegandeliveryoficial.com.br/wp-content/uploads/2021/02/camarao-de-soja-300g-goshen.jpg', 5, 100);
insert into tb_product (name,brand,description,is_vegan,is_vegetarian,is_gluten_free,price,image_url,rating,qnt_stock) values ('Linguiça Calabresa Vegana 300g Goshen', 'Vegano pela vida', 'A Linguiça de soja da Goshen Alimentos é um produto de textura macia, muito saborosa e combina com vários tipos de pratos para o cardápio.', TRUE, TRUE, FALSE, 22.30,'https://www.zonacerealista.com.br/media/catalog/product/cache/1/image/736x460/9df78eab33525d08d6e5fb8d27136e95/0/0/003548_h.jpg', 3, 3);
insert into tb_product (name,brand,description,is_vegan,is_vegetarian,is_gluten_free,price,image_url,rating,qnt_stock) values ('Cream Cheese Vegano 150g Basi.co', 'Vegano pela vida', 'O cream cheese basi.co é feito de castanha de caju de primeira qualidade. Com uma textura característica e aroma idêntico ao natural!', TRUE, FALSE, TRUE, 15.90,'https://veganopelavida.com.br/wp-content/uploads/2021/09/creamcheese.jpg', 4, 10);
insert into tb_product (name,brand,description,is_vegan,is_vegetarian,is_gluten_free,price,image_url,rating,qnt_stock) values ('Molho Branco Vegano Fugini 250g', 'Casa Veg', 'A Molho Branco Vegano Fugini 250g é uma excelente alternativa 100% vegetal ao molho branco tradicional.', TRUE, TRUE, TRUE, 4.70,'https://casaveg.com.br/2066-large_default/molho-branco-vegano-fugini-250g.jpg', 4, 60);
insert into tb_product (name,brand,description,is_vegan,is_vegetarian,is_gluten_free,price,image_url,rating,qnt_stock) values ('Almôndega Vegetariana Mr Veggy 325g', 'Zona Cerealista', 'As nossas Almôndegas Vegetarianas são feitas de proteína texturizada de soja e temperos naturais fresquinhos da horta.', TRUE, TRUE, FALSE, 23.19,'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTMizLb5qDHnlBwBmDZIQaNi3zwschgZdr8MYcpIf0TuB9QZ-3WUTxqeNAp-MyEBH3JG5gpMoZ23D9DlUA0sfNCoSF671l_C9g_Yo2ALTkBOzLiFwpqxcijLg', 5, 50);
insert into tb_product (name,brand,description,is_vegan,is_vegetarian,is_gluten_free,price,image_url,rating,qnt_stock) values ('Feijoada de Qualidade Vegana 450g Goshen', 'Emporio 4 Estrelas', 'Sem lactose. Sem ovo. Sem açucar. Vegetariano e vegano.', TRUE, TRUE, FALSE, 27.90,'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQPct4z_1_V5gRYsX8Dyg9LYU7kh03AApA45Y1Ahwre0B4Zduco99_un130MV0qX40AZXLV6y0tk2_ol4u_Ly7RmVCh_Z8-bflU6kDusc72i9N94tRSwt0XL4BQ&usqp=CAY', 2, 30);
insert into tb_product (name,brand,description,is_vegan,is_vegetarian,is_gluten_free,price,image_url,rating,qnt_stock) values ('Pão Multigrãos Sem Glúten 350g Jasmine', 'Emporio 4 Estrelas', 'Sem lactose. Sem ovo. Sem conservante. Sem glúten. Sem transgênicos. Vegetariano e vegano.', TRUE, TRUE, TRUE, 18.09,'https://mfresh.s3.amazonaws.com/uploads/product/sku/9486/image/3b9102ea-b05b-4d1f-94b9-f352c249bbf2.jpg', 3, 150);

insert into tb_cart (cart_id, created_date) values (1, sysdate);

insert into tb_cart_product (cart_id, product_id) values (1,1);
insert into tb_cart_product (cart_id, product_id) values (1,2);
insert into tb_cart_product (cart_id, product_id) values (1,3);
insert into tb_cart_product (cart_id, product_id) values (1,5);